monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra0"
      }
      {
        node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1"
      }
      {
        node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2"
      }
      {
        node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3"
      }

    ]
    actions = {
      update-props = {
        node.description = "TV"
        node.nick = "TV"
        device.description = "TV"
        device.nick = "TV"
        media.name = "TV"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "USB 2"
        node.nick = "USB 2"
        media.name = "USB 2"
        device.description = "USB 2"
        device.nick = "USB 2"
        device.product.name = "USB 2"
        api.alsa.card.name = "USB 2"
        alsa.card_name = "USB 2"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-R__DE_RODECaster_Duo_IR0040915-00.pro-output-1"
      }
    ]
    actions = {
      update-props = {
        node.description = "z DONT USE THIS (RODECaster Main)"
        node.nick = "z DONT USE THIS (RODECaster Main)"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-R__DE_RODECaster_Duo_IR0040915-00.pro-output-0"
      }
    ]
    actions = {
      update-props = {
        node.description = "Chat"
        node.nick = "Chat"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.usb-R__DE_RODECaster_Duo_IR0040915-00.pro-input-0" }
    ]
    actions = {
      update-props = {
        node.description = "Chat Mic"
        node.nick = "Chat Mic"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.usb-R__DE_RODECaster_Duo_IR0040915-00.pro-input-1" }
    ]
    actions = {
      update-props = {
        node.description = "USB 1 Mic"
        node.nick = "USB 1 Mic"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_input.usb-R__DE_R__DECaster_Duo-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "USB 2 Mic"
        node.nick = "USB 2 Mic"
      }
    }
  }
]
