monitor.stream.rules = [
  {
    matches = [
      {
        application.process.binary = "Cider"
      }
    ]
    actions = {
      update-props = {
        node.autoconnect = false
        target.object = "RODE_Music"
      }
    }
  }
]
