FROM archlinux:latest

RUN useradd -m testuser && \
  echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# install git
RUN pacman -Syu --noconfirm git sudo base-devel

# Create isolated user

USER testuser
WORKDIR /home/testuser



COPY .dots-tests/arch-packages.txt /tmp/packages.txt
COPY .dots-tests/install-arch.sh /home/testuser/install.sh


# Launch shell for interactive testing
CMD ["bash", "/home/testuser/install.sh"]

