FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive


# fd binary fix
RUN ln -s /usr/bin/fdfind /usr/bin/fd

# Isolated user
RUN useradd -m -s /usr/bin/zsh testuser && \
  echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER testuser
WORKDIR /home/testuser


CMD ["bash", "-l"]

